name: Deploy Laravel Application to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Composer dependencies
      run: composer update
      # run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Sync files to VPS
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
        TARGET: "/var/www/html/glennraya.com"

    - name: Run remote commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/glennraya.com
          php artisan migrate --force
          php artisan optimize
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
